@@include('files/regular.js', {})
@@include('files/functions.js', {})
@@include('files/header.js', {})
@@include('files/script.js', {})
@@include('files/dynamic_adapt.js', {})
// @@include('files/forms.js', {})
@@include('files/scroll.js', {})